// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSummary(arg1) {
  return window['go']['main']['App']['GenerateSummary'](arg1);
}

export function GenerateText(arg1, arg2) {
  return window['go']['main']['App']['GenerateText'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadCanvasFromFile() {
  return window['go']['main']['App']['LoadCanvasFromFile']();
}

export function SaveCanvasToFile(arg1) {
  return window['go']['main']['App']['SaveCanvasToFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
