// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GenerateImage(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function GenerateSummary(arg1:string):Promise<string>;

export function GenerateText(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<backend.Config>;

export function GetImageDataURL(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportFile(arg1:string):Promise<backend.ImportFileResult>;

export function LoadCanvasFromFile():Promise<string>;

export function SaveCanvasToFile(arg1:string):Promise<string>;

export function SaveConfig(arg1:backend.Config):Promise<void>;
